### ISSUE TITLE
Wrong language pl_PL.csv file

### ISSUE THREAD

**Issue by MatasDIP** [mageplaza/magento-2-portuguese-language-pack#2]
Wrong csv file in this repo: pl_PL.csv
This is from Polish language pack: https://github.com/mageplaza/magento-2-polish-language-pack

**Comment by zebeel** [comment]
Excuse me, can you tell me more detail about that?
Thank you!

**Comment by MatasDIP** [comment]
This csv file is not from portuguese pack, this file is in polish, i think this file added by mistake.


![screenshot-github com-2018 06 18-11-19-09](https://user-images.githubusercontent.com/17311013/41525407-8c1d0362-72e9-11e8-871a-e48be75658d1.png)

**Comment by zebeel** [comment]
Thank you very much, we will fix it soon.
